-- MySQL Script generated by MySQL Workbench
-- Jum 20 Mar 2015 06:16:14  WIB
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_online_printing
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_online_printing` DEFAULT CHARACTER SET latin1 ;
USE `db_online_printing` ;

-- -----------------------------------------------------
-- Table `db_online_printing`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_online_printing`.`member` (
  `member_username` VARCHAR(32) NOT NULL,
  `member_name` VARCHAR(100) NOT NULL,
  `member_pass` VARCHAR(64) NOT NULL,
  `member_phone` VARCHAR(16) NOT NULL,
  `member_email` VARCHAR(50) NOT NULL,
  `member_address` VARCHAR(100) NOT NULL,
  `member_join` DATETIME NOT NULL,
  PRIMARY KEY (`member_username`),
  UNIQUE INDEX `member_email_UNIQUE` (`member_email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_online_printing`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_online_printing`.`admin` (
  `admin_username` VARCHAR(32) NOT NULL,
  `admin_pass` VARCHAR(64) NOT NULL,
  `admin_name` VARCHAR(100) NOT NULL,
  `admin_email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`admin_username`),
  UNIQUE INDEX `admin_email_UNIQUE` (`admin_email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_online_printing`.`transaksi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_online_printing`.`transaksi` (
  `transaksi_ID` INT NOT NULL AUTO_INCREMENT,
  `transaksi_open` DATETIME NOT NULL,
  `transaksi_payment` MEDIUMBLOB NOT NULL,
  `transaksi_approve` DATETIME NULL,
  `transaksi_close` DATETIME NULL,
  `transaksi_total` INT NOT NULL,
  `member_member_username` VARCHAR(32) NOT NULL,
  `admin_admin_username` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`transaksi_ID`),
  INDEX `fk_transaksi_member1_idx` (`member_member_username` ASC),
  INDEX `fk_transaksi_admin1_idx` (`admin_admin_username` ASC),
  CONSTRAINT `fk_transaksi_member1`
    FOREIGN KEY (`member_member_username`)
    REFERENCES `db_online_printing`.`member` (`member_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaksi_admin1`
    FOREIGN KEY (`admin_admin_username`)
    REFERENCES `db_online_printing`.`admin` (`admin_username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_online_printing`.`service_det`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_online_printing`.`service_det` (
  `service_ID` INT NOT NULL AUTO_INCREMENT,
  `service_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`service_ID`),
  UNIQUE INDEX `service_name_UNIQUE` (`service_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_online_printing`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_online_printing`.`service` (
  `service_ID` INT NOT NULL AUTO_INCREMENT,
  `service_size` VARCHAR(16) NOT NULL,
  `service_price` INT NOT NULL,
  PRIMARY KEY (`service_ID`, `service_size`),
  CONSTRAINT `fk_service_service_det1`
    FOREIGN KEY (`service_ID`)
    REFERENCES `db_online_printing`.`service_det` (`service_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_online_printing`.`transaksi_det`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_online_printing`.`transaksi_det` (
  `transaksi_det_ID` INT NOT NULL AUTO_INCREMENT,
  `transaksi_ID` INT NOT NULL,
  `service_ID` INT NOT NULL,
  `file_print` MEDIUMBLOB NOT NULL,
  `quantity` INT NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`transaksi_det_ID`, `transaksi_ID`, `service_ID`),
  INDEX `fk_transaksi_det_service1_idx` (`service_ID` ASC),
  CONSTRAINT `fk_transaksi_det_transaksi1`
    FOREIGN KEY (`transaksi_ID`)
    REFERENCES `db_online_printing`.`transaksi` (`transaksi_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaksi_det_service1`
    FOREIGN KEY (`service_ID`)
    REFERENCES `db_online_printing`.`service` (`service_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
